### ISSUE TITLE
同一时间收到过多消息，会丢弃一部分连接，丢失一些消息

### ISSUE THREAD

**Issue by ol1u** [ehForwarderBot/efb-wechat-comwechat-slave#25]
当收到别人逐一转发超过10条消息的，会只能成功转发10条消息，其余的将会丢失.

日志如下

> RetryAfter()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/efb_telegram_master/slave_message.py", line 121, in send_message
    self.dispatch_message(msg, msg_template, old_msg_id, tg_dest, silent)
  File "/usr/local/lib/python3.9/dist-packages/efb_telegram_master/slave_message.py", line 172, in dispatch_message
    tg_msg = self.slave_message_text(msg, tg_dest, msg_template, reactions, old_msg_id, target_msg_id,
  File "/usr/local/lib/python3.9/dist-packages/efb_telegram_master/slave_message.py", line 327, in slave_message_text
    tg_msg = self.bot.send_message(tg_dest,
  File "/usr/local/lib/python3.9/dist-packages/efb_telegram_master/bot_manager.py", line 130, in retry_on_chat_migration_wrap
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/efb_telegram_master/bot_manager.py", line 231, in send_message
    return self._bot_send_message_fallback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/efb_telegram_master/bot_manager.py", line 283, in _bot_send_message_fallback
    return self.updater.bot.send_message(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 134, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 534, in send_message
    return self._message(  # type: ignore[return-value]
  File "/usr/local/lib/python3.9/dist-packages/telegram/ext/extbot.py", line 203, in _message
    result = super()._message(
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 344, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 299, in _post
    return self.request.post(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 272, in _request_wrapper
    message = str(self._parse(resp.data))
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 230, in _parse
    raise RetryAfter(retry_after)
telegram.error.RetryAfter: Flood control exceeded. Retry in 5.0 seconds
2023-08-06 05:47:10,751 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: api.telegram.org

**Comment by 0honus0** [comment]
你这个日志看起来是网络连接问题

**Comment by ol1u** [comment]
似乎是telegram官方的限制，无解。[https://github.com/ehForwarderBot/efb-telegram-master/issues/123](url)
